version: "3.7"

services:
  database:
    image: postgres:9.6
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: digi0ps
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: findus

  django:
    build: .
    command: bash -c /code/start.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always

volumes:
  postgres-data:
