# Generated by Django 2.2.6 on 2019-10-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, default='Anon', max_length=50)),
                ('encoding', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FaceEncoding')),
            ],
        ),
    ]
