# Generated by Django 2.2.6 on 2019-10-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191015_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
