# Generated by Django 2.2.6 on 2019-10-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191015_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FaceEncoding'),
        ),
    ]
