# Generated by Django 2.2.6 on 2019-10-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_photo_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='persons',
        ),
        migrations.AddField(
            model_name='photo',
            name='persons',
            field=models.ManyToManyField(null=True, to='api.FaceEncoding'),
        ),
    ]
